"""Deterministic BaiJiangPai simulation and rule-policy interfaces."""

from ok_tasks.card_ai.engine import BaiJiangPaiEngine, SimulationError
from ok_tasks.card_ai.hero_policy import (
    HeroDecisionContext,
    ProjectionBranch,
    SkillChoice,
    SkillProjection,
    TRIGGER_HANDLERS,
    apply_skill_choice,
    enumerate_skill_choices,
    evaluate_play,
    select_skill_choice,
    trigger_handler_for,
)
from ok_tasks.card_ai.heroes import (
    AUTHORITATIVE_RULE_IDS,
    AUTHORITATIVE_SKILL_NAMES,
    HERO_ALIASES,
    HERO_MECHANISM_GROUPS,
    HERO_PRIMARY_MECHANISM,
    HERO_REGISTRY,
    OWNED_HEROES,
    T0_HEROES,
    T1_HEROES,
    POLICY_SIMULATED_HEROES,
    SIMULATED_HEROES,
)
from ok_tasks.card_ai.schema import (
    CardInstance,
    FullGameState,
    HeroSkillSpec,
    LegalAction,
    Observation,
    PlayerState,
    StepResult,
    TrajectoryEvent,
)

__all__ = [
    "BaiJiangPaiEngine",
    "AUTHORITATIVE_RULE_IDS",
    "AUTHORITATIVE_SKILL_NAMES",
    "CardInstance",
    "FullGameState",
    "HERO_ALIASES",
    "HERO_MECHANISM_GROUPS",
    "HERO_PRIMARY_MECHANISM",
    "HERO_REGISTRY",
    "HeroDecisionContext",
    "HeroSkillSpec",
    "LegalAction",
    "OWNED_HEROES",
    "T0_HEROES",
    "T1_HEROES",
    "Observation",
    "PlayerState",
    "POLICY_SIMULATED_HEROES",
    "ProjectionBranch",
    "SimulationError",
    "SIMULATED_HEROES",
    "SkillChoice",
    "SkillProjection",
    "TRIGGER_HANDLERS",
    "StepResult",
    "TrajectoryEvent",
    "apply_skill_choice",
    "enumerate_skill_choices",
    "evaluate_play",
    "select_skill_choice",
    "trigger_handler_for",
]
